In [384]:
import numpy as np  
import pandas as pd  
import matplotlib.pyplot as plt  
from scipy.io import loadmat  
import seaborn as sbs
import matplotlib.image as mpimg
import scipy.optimize as op
from scipy.optimize import minimize
%matplotlib inline


In [385]:
#%% Setup the parameters you will use for this exercise
input_layer_size  = 400;  #% 20x20 Input Images of Digits
hidden_layer_size = 25;   #% 25 hidden units
num_labels = 10; #% 10 labels, from 1 to 10 (note that we have mapped "0" to label 10)

In [386]:
data = loadmat('ex4data1.mat');
X=data['X']
y=data['y']
m,n = X.shape
#% Randomly select 100 data points to display
rand_indices = np.random.permutation(m)
train_number = int(m/3.0*2.0)
#X_train = X[rand_indices[0:train_number], :];
#y_train = y[rand_indices[0:train_number], :];
#X_test = X[rand_indices[train_number:], :];
#y_test = y[rand_indices[train_number:], :];
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y) #split data to train and test

The neural network may have difficulty converging before the maximum number of iterations allowed 
if the data is not normalized. Multi-layer Perceptron is sensitive to feature scaling, so it is 
highly recommended to scale your data. Note that you must apply the same scaling to the test set for 
meaningful results. There are a lot of different methods for normalization of data, we will use the 
built-in StandardScaler for standardization.

In [387]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
# Fit only to the training data
#scaler.fit(X_train)
#StandardScaler(copy=True, with_mean=True, with_std=True)
#X_train = scaler.transform(X_train)
#X_test = scaler.transform(X_test)

In [458]:
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(activation='relu',solver='adam',alpha=0.25,hidden_layer_sizes=(100,50,50,50),learning_rate='adaptive',
                    learning_rate_init=0.01,max_iter=50000,tol=0.0001,verbose=False)
mlp.fit(X_train,y_train)

MLPClassifier(activation='relu', alpha=0.25, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100, 50, 50, 50), learning_rate='adaptive',
       learning_rate_init=0.01, max_iter=50000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [459]:
predictions = mlp.predict(X_test)

In [460]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,predictions))

[[109   0   1   0   0   0   2   2   0   0]
 [  0 106   1   2   0   3   2  11   0   1]
 [  0   0 113   0   0   0   1   1   2   0]
 [  1   0   0 125   0   3   0   2   0   1]
 [  0   0   1   2 110   0   0   3   1   1]
 [  0   0   0   0   1 124   0   0   0   3]
 [  0   1   0   1   0   0 121   0   1   1]
 [  0   0   0   1   0   0   1 129   1   1]
 [  0   0   0   4   0   0   4   1 126   0]
 [  0   0   1   0   0   0   0   1   0 120]]


In [461]:
print(classification_report(y_test,predictions))

             precision    recall  f1-score   support

          1       0.99      0.96      0.97       114
          2       0.99      0.84      0.91       126
          3       0.97      0.97      0.97       117
          4       0.93      0.95      0.94       132
          5       0.99      0.93      0.96       118
          6       0.95      0.97      0.96       128
          7       0.92      0.97      0.95       125
          8       0.86      0.97      0.91       133
          9       0.96      0.93      0.95       135
         10       0.94      0.98      0.96       122

avg / total       0.95      0.95      0.95      1250



In [462]:
mlp.score

<bound method MLPClassifier.score of MLPClassifier(activation='relu', alpha=0.25, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100, 50, 50, 50), learning_rate='adaptive',
       learning_rate_init=0.01, max_iter=50000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)>